# Generated by Django 5.0.6 on 2024-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=0, upload_to='recipes/images/'),
            preserve_default=False,
        ),
    ]
