# Generated by Django 5.0.6 on 2024-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_category_alter_recipe_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='recipes/categoryImages/'),
        ),
    ]
